spring.application.name=aqua-equity-api

spring.datasource.url=jdbc:mysql://qe71st.h.filess.io:3307/aqua_equity_greaterlow?useSSL=false&serverTimezone=UTC
spring.datasource.username=aqua_equity_greaterlow
spring.datasource.password=586798d703e7f33f1bd4aa0d0d2222cb4c13926f
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
